# Change these first
owner: AjibsBaba # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Portfolio Website
    url: https://www.ajibsbaba.com
  - name: TRM Web App
    url: https://trm.ajibsbaba.com

assignees: 
  - AjibsBaba

status-website:
  theme: light
  cname: uptime.ajibsbaba.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "This is an uptime monitor and status page for AjibsBaba's Projects"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/AjibsBaba/uptime).
  navbar:
    - title: Status
      href: /
    - title: AjibsBaba
      href: https://ajibsbaba.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
